name: CI

on:
  push:
    branches: ['**']

jobs:
  lint:
    name: 'Lint'
    runs-on: 'ubuntu-18.04'
    steps:
      - uses: 'actions/checkout@v2.3.4'
      - uses: 'actions/setup-python@v2'
        with:
          python-version: '3.9'
      - name: 'Install dependencies'
        run: |
          echo "Installing CI requirements"
          pip install --upgrade --user pip flake8
          echo "Installing project requirements"
          pip install -r requirements.txt
      - name: 'Flake8 :allthethings:'
        run: |
          python -m flake8 --max-line-length 120
  container_build:
    needs: ['lint']
    name: 'Build and Push Docker Container'
    runs-on: 'ubuntu-18.04'
    steps:
    - uses: 'actions/checkout@v2.3.4'
    - name: 'Build the Docker image'
      run: |
        docker build . -t chrisjohnson00/qbittorrent-tool-clear-errored:${GITHUB_REF##*/}
    - name: 'Login to docker hub'
      run: |
        docker login --username=chrisjohnson00 --password=${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: 'Push the Docker image'
      run: |
        docker push chrisjohnson00/qbittorrent-tool-clear-errored:${GITHUB_REF##*/}
  actionslint:
    name: 'Actions Yaml Lint'
    runs-on: 'ubuntu-18.04'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2.3.4'
      - name: 'Actions Yaml Lint'
        uses: 'karancode/yamllint-github-action@v2.0.0'
        with:
          yamllint_file_or_dir: '.github/workflows'
          yamllint_comment: true
          yamllint_config_filepath: '.yamllint'
        env:
          GITHUB_ACCESS_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
